version: '3.8'

networks: 
    mysql-compose-network:
      driver: bridge

volumes:
    mysql_vol:     
    wordpress:

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
           
    depends_on:
      - mysql
    networks:
      - mysql-compose-network
    
  mysql:
    image: mysql:8.0
    restart: always
     
    networks:
      - mysql-compose-network  
    volumes:
      - mysql_vol:/var/lib/mysql
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'